console.log("\n\tCommands:")
console.log("\n\t->dev: run this command to run the ts compiler with hot reload.")
console.log("\n\t->start: run this command to run the application.")
console.log("\n\t->setup: this command is used with an extra parameter to setup AWS resources.")
console.log("\n\t->clean: this command is used with an extra parameter to clean(delete) AWS resources.")
console.log("\n\n\t\textra parameters: extra parameters to be used with 'clean' and 'setup'")
console.log("\n\t\t->all: all resources")
console.log("\n\t\t->dynamoDB: only dynamoDB")
console.log("\n\t\t->APIGateway: only APIGateway")